### ISSUE TITLE
Move additionalProperties from DefaultProblem to Problem

### ISSUE THREAD

**Issue by jpraet** [belgif/rest-problem-java#1]
An additionalProperties with JsonAnyGetter/JsonAnySetter is currently defined on DefaultProblem (the fallback class for unmapped problem types).

It would be better if these additionalProperties would be pulled up into the Problem base class, so we can handle properties that have not been defined in the schema for any problem.

But this requires upgrading to jackson-databind 2.16.2 because of https://github.com/FasterXML/jackson-databind/issues/4316, and I don't think we want to tie the rest-problem-java library to a specific jackson version.

**Comment by pvdbosch** [comment]
We could require a minimum jackson version, but it should cover most versions that are currently in use; 2.16.2 is too new.

**Comment by jpraet** [comment]
We currently have integration tests with Spring Boot 2.7.18 (jackson 2.13.5) and JBoss EAP 7.4 (jackson 2.12.7).
