### ISSUE TITLE
Add Bean Validation support to belgif-rest-problem-spring

### ISSUE THREAD

**Issue by jpraet** [belgif/rest-problem-java#12]
At CBSS, we don't (currently) use Spring Boot for implementing REST APIs. So the belgif-rest-problem-spring library is not completely on par with the belgif-rest-problem-java-ee library.

One of the lacking features is [Bean Validation](https://docs.spring.io/spring-framework/reference/core/validation/beanvalidation.html) support.

More specifically, an ExceptionMapper for converting whatever exception the Spring Framework throws in case of a Bean Validation constraint violation, to a BadRequestProblem, similar to what is done in belgif-rest-problem-java-ee with
[ConstraintViolationExceptionMapper](https://github.com/belgif/rest-problem-java/blob/main/belgif-rest-problem-java-ee/src/main/java/io/github/belgif/rest/problem/jaxrs/ConstraintViolationExceptionMapper.java) and [ConstraintViolationUtil](https://github.com/belgif/rest-problem-java/blob/main/belgif-rest-problem-java-ee/src/main/java/io/github/belgif/rest/problem/internal/ConstraintViolationUtil.java).

**Comment by smals-mavh** [comment]
Created pull request, ready for review
