### ISSUE TITLE
Extract validators

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-problem-java#16]
The library contains a list of input validators (e.g. validate period end after start, SSIN checksum, ...).

Smals uses another library for validation, based on Bean Validation annotations: https://www.ict-reuse.be/nl/service/smalsutils-validation . These annotations are added to the generated code by adding "x-[...]-extra-annotation" properties in the OpenAPI document.

I suggest to:
* define a standard way how input validation errors can be propagated in a way the rest-problem-java library can handle them
* extract validators out of the rest-problem-java library
* (optional) refactor/improve a common validation library

**Comment by jpraet** [comment]
OK to extract to belgif-rest-problem-validator maven module within the same repo for now?

**Comment by pvdbosch** [comment]
I'd prefer to move it out of the repo before we're starting to use the library to avoid developers using it already and then having to support it. Until then, it can remain in and we can ignore it during testing.

**Comment by jpraet** [comment]
The RequestValidator overlaps with this subset of the Smals validation library:
* SSIN
* enteprise number
* establishment unit number 
* incomplete date

The RequestValidator additionally implements these cross-parameter validations:
* period
* exactlyOneOf
* anyOf
* zeroOrAllOf
* zeroOrExactlyOneOf
* equal
* nullOrEqual

and these dynamic or context-dependent validations:
* refData
* reject
* require
* range
* minimum
* maximum

At first sight, cross-parameter validations and dynamic or context-dependent validations seem not well suited for the Smals validator approach with x-extra-annotation? I think both libraries could coexist.

In any case, we can initially extract the RequestValidator to a separate belgif-rest-problem-validator module within the repo.

**Comment by pvdbosch** [comment]
OK, will need some more analysis which can be done later. Maybe both programmatic and declarative (annotation) validations can be combined in a single library.
Period validation could be doable with an annotation if a schema of time-v1 is used, but probably not for query params.
