### ISSUE TITLE
Add core users of rest-problem-java library to DEFAULT_SCAN_PACKAGES of SpringProblemTypeRegistry

### ISSUE THREAD

**Issue by jpraet** [belgif/rest-problem-java#2]
SpringProblemTypeRegistry uses classpath scanning for discovering @ProblemTypes.

By default, it currently scans these base packages:
* io.github.belgif.rest.problem
* be.fgov.kszbcss

Additional packages can be configured with the `io.github.belgif.rest.problem.spring.scan-additional-problem-packages` property. For convenience, the base packages of the core users of the rest-problem-java library could be added to the default list.

**Comment by pvdbosch** [comment]
Do we need to maintain a central list? Maybe it's possible to maintain organization-specific defaults in an organization-specific library. We're trying out use of `@PropertySource` as described in https://stackoverflow.com/a/28894906 .
We'll probably need such a library anyway e.g. for jackson serialization defaults.

**Comment by pvdbosch** [comment]
> Shall I remove `be.fgov.kszbcss` from the default packages then?

Yes, that's OK for me.
