### ISSUE TITLE
Remove deprecated status and instance properties in InputValidationIssue

### ISSUE THREAD

**Issue by jpraet** [belgif/rest-problem-java#35]
We can probably remove the deprecated status and instance properties in [InputValidationIssue](https://github.com/belgif/rest-problem-java/blob/main/belgif-rest-problem/src/main/java/io/github/belgif/rest/problem/api/InputValidationIssue.java).
They exist because InputValidationIssue extends Problem in [problem-v1.yaml](https://github.com/belgif/openapi-problem/blob/6a89c0720a89d34c76f8e063c5856a7b2d64b389/src/main/openapi/problem/v1/problem-v1.yaml#L135), but they are not supposed to be used.

InputValidationIssue supports additionalProperties, so if really needed, these deprecated properties could still be used there.

**Comment by jpraet** [comment]
@pvdbosch is the "instance" property on InputValidationIssue discouraged or not?
Only "status" is officially mentioned in https://github.com/belgif/openapi-problem/blob/6a89c0720a89d34c76f8e063c5856a7b2d64b389/src/main/openapi/problem/v1/problem-v1.yaml#L131.

**Comment by pvdbosch** [comment]
This has not yet been discussed AFAIK, but for most use cases, I don't think an identifier for each individual issue is useful and worthwhile. Usually, a single `instance` value on the InputValidationProblem should be sufficient.

**Comment by jpraet** [comment]
Ah, it came from a review comment on the rest-support library:

![image](https://github.com/belgif/rest-problem-java/assets/2212615/f9b499c1-2224-4a48-8e3a-17c2f49b86e0)

So in my opinion we can remove the properties if they are not intended to be used.
As fallback, they can be added/retrieved via the additionalProperties.
