### ISSUE TITLE
Consider adding a "nullOrNotBlank" method to RequestValidator

### ISSUE THREAD

**Issue by clone1612** [belgif/rest-problem-java#58]
The OpenAPI generator plugin doesn't add `@NotBlank/@NotEmpty` annotations to the generated interfaces: https://stackoverflow.com/questions/77515177/openapi-generator-do-not-insert-notblank-annotation-for-string

A workaround is to add `x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"` hints to the schema, but that's not exactly clean. As not all parameters have a regex we can use to enforce certain content we sometimes have to check that in our code.

The idea would be to add a `nullOrNotBlank(Input<String>... inputs)` method to the `RequestValidator` that allows us to integrate that check with others in the validator (without resorting to the more verbose `.custom(...)` method). Maybe it's a bit too specific? What do you think?

**Comment by jpraet** [comment]
The RequestValidator is mainly meant for validations that cannot be enforced through the openapi schema.

* for a non-empty string, you can define `minLength: 1` in the openapi schema
* for a non-blank string, you can define `pattern: \S` in the openapi schema
