### ISSUE TITLE
[spring] Map NoResourceFoundException

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-problem-java#72]
When navigating to a URL that isn't mapped to a RestController, a NoResourceFoundException is thrown.

This exception currently results in a internalServerError problem type (default mapping); but should be a 404 resourceNotFound one.

**Comment by jpraet** [comment]
I observed that with the integration tests too:

https://github.com/belgif/rest-problem-java/blob/4c893ad28475a2335b7e9faf51c3f357abc8fda6/belgif-rest-problem-it/belgif-rest-problem-spring-boot-3-it/src/test/java/io/github/belgif/rest/problem/RestProblemSpringBoot3IT.java#L29-L33

The [NoResourceFoundException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/resource/NoResourceFoundException.html) is new in Spring Boot 3.2 / Spring Framework 6.1 though. 
We may need to add a separate module for Spring Boot 3.x then, or drop support for 2.x.
