### ISSUE TITLE
Bug: parameter name not correctly retrieved from interface

### ISSUE THREAD

**Issue by smals-mavh** [belgif/rest-problem-java#96]
Got the following response from a Spring Boot 3.3.3 application:
```
{
    "type": "urn:problem-type:belgif:badRequest",
    "href": "https://www.belgif.be/specification/rest/api-guide/problems/badRequest.html",
    "title": "Bad Request",
    "status": 400,
    "detail": "The input message is incorrect",
    "issues": [
        {
            "type": "urn:problem-type:belgif:input-validation:schemaViolation",
            "title": "Input value is invalid with respect to the schema",
            "detail": "must be greater than or equal to 197",
            "in": "path",
            "name": "arg0",
            "value": 160
        }
    ]
}
```
Parameter annotations are only present on the (generated) interface, not on the implementation (when adding annotation to the implementation, 'name' is filled in correctly). Probably something goes wrong in reading the annotations of the parent class / interface.

**Comment by jpraet** [comment]
That being said, it would probably be better if the parameter name could be extracted from annotations like PathVariable, RequestParam and RequestHeader. The name of the java method param does not necessarily match the name in the annotation.

This should be achievable with a [ParameterNameProvider](https://jakarta.ee/specifications/platform/10/apidocs/jakarta/validation/parameternameprovider).
